# Generated by Django 2.2.6 on 2019-12-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0002_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='carriers',
            name='fileuploads',
            field=models.ImageField(default=1, upload_to='beautyapp/Images'),
            preserve_default=False,
        ),
    ]
