# Generated by Django 2.2.6 on 2019-12-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0004_auto_20191206_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carriers',
            name='profile_pic',
        ),
    ]
