# Generated by Django 2.2 on 2019-12-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0005_remove_carriers_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriers',
            name='fileupload',
            field=models.FileField(upload_to='resume/'),
        ),
    ]
