# Generated by Django 2.2.6 on 2019-12-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0007_auto_20191207_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='carriers',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='Images/img/'),
            preserve_default=False,
        ),
    ]
