# Generated by Django 2.2.6 on 2019-12-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0008_carriers_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='duration',
            field=models.CharField(default='60 minutes', max_length=200),
        ),
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(default='Services', max_length=500),
        ),
    ]
