# Generated by Django 2.2.6 on 2019-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0009_auto_20191209_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(default='0.00'),
        ),
    ]
