# Generated by Django 2.2.6 on 2019-12-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0010_auto_20191209_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='services',
            name='price',
        ),
    ]
